### ISSUE TITLE
Option to allow all imports from certain modules

### ISSUE THREAD

**Issue by ljodal** [kolonialno/oida#19]
From #17 the need for allowing all imports from a certain module was raised. Ie. a common module with general utilities that are intended to be used everywhere. Maybe we could add an option to `pyproject.toml`, something like this maybe?

```toml
[oida]
allowed_imports = [
    "foo.utils.*",
]
```
